/* The following code was generated by JFlex 1.6.1 */

package go.core;

import java_cup.runtime.*;
/*

    OBSERVAÇÕES:

    Especificação do GO: https://golang.org/ref/spec#unicode_letter
    Exemplo para a linguagem JAVA: https://github.com/moy/JFlex/blob/master/jflex/examples/java/java.flex
    Documentação JFLEX: http://jflex.de/manual.html#ExampleLexRules
    Tutorialzinho legal: https://www.skenz.it/compilers/classroom/practice1_6.pdf
    Projeto de uma galera das antigas com JFLEX/Cup para C: https://github.com/brunomb/CCompiler

    Caracter "_" é considerado uma letra em GO.
    a-f dá matche em todos os caracteres de a até f
    [xX] dá matche em x ou X
    [^] dá matche em TODOS os caracteres
    [.] dá matche em todos os caracteres menos fim de linhas UNICODE

    Unicode letters = [:letter:]
    Unidode digits = [:digit:]

*/


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>eclipseWorkspace/GoTranslator/spec/rules.flex</tt>
 */
public class Lexical implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\5\1\4\1\27\1\30\1\3\22\0\1\56\1\57\1\31"+
    "\2\0\1\75\1\54\1\0\1\60\1\61\1\7\1\53\1\73\1\23"+
    "\1\24\1\6\1\16\7\20\2\2\1\72\1\74\1\63\1\55\1\67"+
    "\2\0\4\17\1\22\1\17\21\1\1\21\2\1\1\64\1\26\1\65"+
    "\1\66\1\13\1\25\1\34\1\32\1\42\1\36\1\11\1\37\1\44"+
    "\1\50\1\15\1\1\1\35\1\14\1\46\1\10\1\45\1\47\1\1"+
    "\1\33\1\43\1\41\1\40\1\52\1\12\1\21\1\51\1\1\1\70"+
    "\1\62\1\71\7\0\1\27\44\0\1\0\12\0\1\0\4\0\1\0"+
    "\5\0\27\0\1\0\37\0\1\0\u01ca\0\4\0\14\0\16\0\5\0"+
    "\7\0\1\0\1\0\1\0\201\0\5\0\1\0\2\0\2\0\4\0"+
    "\1\0\1\0\6\0\1\0\1\0\3\0\1\0\1\0\1\0\24\0"+
    "\1\0\123\0\1\0\213\0\10\0\246\0\1\0\46\0\2\0\1\0"+
    "\7\0\47\0\110\0\33\0\5\0\3\0\55\0\53\0\43\0\2\0"+
    "\1\0\143\0\1\0\1\0\17\0\2\0\7\0\2\0\12\0\3\0"+
    "\2\0\1\0\20\0\1\0\1\0\36\0\35\0\131\0\13\0\1\0"+
    "\30\0\41\0\11\0\2\0\4\0\1\0\5\0\26\0\4\0\1\0"+
    "\11\0\1\0\3\0\1\0\27\0\31\0\107\0\23\0\121\0\66\0"+
    "\3\0\1\0\22\0\1\0\7\0\12\0\17\0\20\0\4\0\10\0"+
    "\2\0\2\0\2\0\26\0\1\0\7\0\1\0\1\0\3\0\4\0"+
    "\3\0\1\0\20\0\1\0\15\0\2\0\1\0\3\0\16\0\2\0"+
    "\23\0\6\0\4\0\2\0\2\0\26\0\1\0\7\0\1\0\2\0"+
    "\1\0\2\0\1\0\2\0\37\0\4\0\1\0\1\0\23\0\3\0"+
    "\20\0\11\0\1\0\3\0\1\0\26\0\1\0\7\0\1\0\2\0"+
    "\1\0\5\0\3\0\1\0\22\0\1\0\17\0\2\0\43\0\10\0"+
    "\2\0\2\0\2\0\26\0\1\0\7\0\1\0\2\0\1\0\5\0"+
    "\3\0\1\0\36\0\2\0\1\0\3\0\17\0\1\0\21\0\1\0"+
    "\1\0\6\0\3\0\3\0\1\0\4\0\3\0\2\0\1\0\1\0"+
    "\1\0\2\0\3\0\2\0\3\0\3\0\3\0\14\0\26\0\1\0"+
    "\64\0\10\0\1\0\3\0\1\0\27\0\1\0\20\0\3\0\1\0"+
    "\32\0\2\0\6\0\2\0\43\0\10\0\1\0\3\0\1\0\27\0"+
    "\1\0\12\0\1\0\5\0\3\0\1\0\40\0\1\0\1\0\2\0"+
    "\17\0\2\0\22\0\10\0\1\0\3\0\1\0\51\0\2\0\1\0"+
    "\20\0\1\0\21\0\2\0\30\0\6\0\5\0\22\0\3\0\30\0"+
    "\1\0\11\0\1\0\1\0\2\0\7\0\72\0\60\0\1\0\2\0"+
    "\14\0\7\0\72\0\2\0\1\0\1\0\2\0\2\0\1\0\1\0"+
    "\2\0\1\0\6\0\4\0\1\0\7\0\1\0\3\0\1\0\1\0"+
    "\1\0\1\0\2\0\2\0\1\0\4\0\1\0\2\0\11\0\1\0"+
    "\2\0\5\0\1\0\1\0\25\0\4\0\40\0\1\0\77\0\10\0"+
    "\1\0\44\0\33\0\5\0\163\0\53\0\24\0\1\0\20\0\6\0"+
    "\4\0\4\0\3\0\1\0\3\0\2\0\7\0\3\0\4\0\15\0"+
    "\14\0\1\0\21\0\46\0\1\0\1\0\5\0\1\0\2\0\53\0"+
    "\1\0\u014d\0\1\0\4\0\2\0\7\0\1\0\1\0\1\0\4\0"+
    "\2\0\51\0\1\0\4\0\2\0\41\0\1\0\4\0\2\0\7\0"+
    "\1\0\1\0\1\0\4\0\2\0\17\0\1\0\71\0\1\0\4\0"+
    "\2\0\103\0\45\0\20\0\20\0\125\0\14\0\u026c\0\2\0\21\0"+
    "\1\0\32\0\5\0\113\0\6\0\10\0\7\0\15\0\1\0\4\0"+
    "\16\0\22\0\16\0\22\0\16\0\15\0\1\0\3\0\17\0\64\0"+
    "\43\0\1\0\4\0\1\0\103\0\130\0\10\0\51\0\1\0\1\0"+
    "\5\0\106\0\12\0\37\0\61\0\36\0\2\0\5\0\13\0\54\0"+
    "\25\0\7\0\70\0\27\0\11\0\65\0\122\0\1\0\135\0\57\0"+
    "\21\0\7\0\67\0\36\0\15\0\2\0\12\0\54\0\32\0\44\0"+
    "\51\0\3\0\12\0\44\0\153\0\4\0\1\0\4\0\3\0\2\0"+
    "\11\0\300\0\100\0\u0116\0\2\0\6\0\2\0\46\0\2\0\6\0"+
    "\2\0\10\0\1\0\1\0\1\0\1\0\1\0\1\0\1\0\37\0"+
    "\2\0\65\0\1\0\7\0\1\0\1\0\3\0\3\0\1\0\7\0"+
    "\3\0\4\0\2\0\6\0\4\0\15\0\5\0\3\0\1\0\7\0"+
    "\53\0\1\27\1\27\107\0\1\0\15\0\1\0\20\0\15\0\145\0"+
    "\1\0\4\0\1\0\2\0\12\0\1\0\1\0\3\0\5\0\6\0"+
    "\1\0\1\0\1\0\1\0\1\0\1\0\4\0\1\0\13\0\2\0"+
    "\4\0\5\0\5\0\4\0\1\0\64\0\2\0\u0a7b\0\57\0\1\0"+
    "\57\0\1\0\205\0\6\0\4\0\3\0\2\0\14\0\46\0\1\0"+
    "\1\0\5\0\1\0\2\0\70\0\7\0\1\0\20\0\27\0\11\0"+
    "\7\0\1\0\7\0\1\0\7\0\1\0\7\0\1\0\7\0\1\0"+
    "\7\0\1\0\7\0\1\0\7\0\120\0\1\0\u01d5\0\2\0\52\0"+
    "\5\0\5\0\2\0\4\0\126\0\6\0\3\0\1\0\132\0\1\0"+
    "\4\0\5\0\51\0\3\0\136\0\21\0\33\0\65\0\20\0\u0200\0"+
    "\u19b6\0\112\0\u51cd\0\63\0\u048d\0\103\0\56\0\2\0\u010d\0\3\0"+
    "\20\0\12\0\2\0\24\0\57\0\20\0\37\0\2\0\106\0\61\0"+
    "\11\0\2\0\147\0\2\0\4\0\1\0\36\0\2\0\2\0\105\0"+
    "\13\0\1\0\3\0\1\0\4\0\1\0\27\0\35\0\64\0\16\0"+
    "\62\0\76\0\6\0\3\0\1\0\16\0\34\0\12\0\27\0\31\0"+
    "\35\0\7\0\57\0\34\0\1\0\20\0\5\0\1\0\12\0\12\0"+
    "\5\0\1\0\51\0\27\0\3\0\1\0\10\0\24\0\27\0\3\0"+
    "\1\0\3\0\62\0\1\0\1\0\3\0\2\0\2\0\5\0\2\0"+
    "\1\0\1\0\1\0\30\0\3\0\2\0\13\0\7\0\3\0\14\0"+
    "\6\0\2\0\6\0\2\0\6\0\11\0\7\0\1\0\7\0\1\0"+
    "\53\0\1\0\4\0\4\0\2\0\132\0\43\0\35\0\u2ba4\0\14\0"+
    "\27\0\4\0\61\0\u2104\0\u016e\0\2\0\152\0\46\0\7\0\14\0"+
    "\5\0\5\0\1\0\1\0\12\0\1\0\15\0\1\0\5\0\1\0"+
    "\1\0\1\0\2\0\1\0\2\0\1\0\154\0\41\0\u016b\0\22\0"+
    "\100\0\2\0\66\0\50\0\14\0\164\0\5\0\1\0\207\0\44\0"+
    "\32\0\6\0\32\0\13\0\131\0\3\0\6\0\2\0\6\0\2\0"+
    "\6\0\2\0\3\0\43\0\14\0\1\0\32\0\1\0\23\0\1\0"+
    "\2\0\1\0\17\0\2\0\16\0\42\0\173\0\u0185\0\35\0\3\0"+
    "\61\0\57\0\40\0\20\0\21\0\1\0\10\0\6\0\46\0\12\0"+
    "\36\0\2\0\44\0\4\0\10\0\60\0\236\0\142\0\50\0\10\0"+
    "\64\0\234\0\u0137\0\11\0\26\0\12\0\10\0\230\0\6\0\2\0"+
    "\1\0\1\0\54\0\1\0\2\0\3\0\1\0\2\0\27\0\12\0"+
    "\27\0\11\0\37\0\141\0\26\0\12\0\32\0\106\0\70\0\6\0"+
    "\2\0\100\0\1\0\17\0\4\0\1\0\3\0\1\0\33\0\54\0"+
    "\35\0\3\0\35\0\43\0\10\0\1\0\34\0\33\0\66\0\12\0"+
    "\26\0\12\0\23\0\15\0\22\0\156\0\111\0\u03ba\0\65\0\113\0"+
    "\55\0\40\0\31\0\32\0\44\0\51\0\43\0\3\0\1\0\14\0"+
    "\60\0\16\0\4\0\25\0\1\0\45\0\22\0\1\0\31\0\204\0"+
    "\57\0\46\0\10\0\2\0\2\0\2\0\26\0\1\0\7\0\1\0"+
    "\2\0\1\0\5\0\3\0\1\0\37\0\5\0\u011e\0\60\0\24\0"+
    "\2\0\1\0\1\0\270\0\57\0\121\0\60\0\24\0\1\0\73\0"+
    "\53\0\u01f5\0\100\0\37\0\1\0\u01c0\0\71\0\u0507\0\u0399\0\u0c67\0"+
    "\u042f\0\u33d1\0\u0239\0\7\0\37\0\161\0\36\0\22\0\60\0\20\0"+
    "\4\0\37\0\25\0\5\0\23\0\u0370\0\105\0\13\0\1\0\102\0"+
    "\15\0\u4060\0\2\0\u0bfe\0\153\0\5\0\15\0\3\0\11\0\7\0"+
    "\12\0\u1766\0\125\0\1\0\107\0\1\0\2\0\2\0\1\0\2\0"+
    "\2\0\2\0\4\0\1\0\14\0\1\0\1\0\1\0\7\0\1\0"+
    "\101\0\1\0\4\0\2\0\10\0\1\0\7\0\1\0\34\0\1\0"+
    "\4\0\1\0\5\0\1\0\1\0\3\0\7\0\1\0\u0154\0\2\0"+
    "\31\0\1\0\31\0\1\0\37\0\1\0\31\0\1\0\37\0\1\0"+
    "\31\0\1\0\37\0\1\0\31\0\1\0\37\0\1\0\31\0\1\0"+
    "\10\0\u1034\0\305\0\u053b\0\4\0\1\0\33\0\1\0\2\0\1\0"+
    "\1\0\2\0\1\0\1\0\12\0\1\0\4\0\1\0\1\0\1\0"+
    "\1\0\6\0\1\0\4\0\1\0\1\0\1\0\1\0\1\0\1\0"+
    "\3\0\1\0\2\0\1\0\1\0\2\0\1\0\1\0\1\0\1\0"+
    "\1\0\1\0\1\0\1\0\1\0\1\0\2\0\1\0\1\0\2\0"+
    "\4\0\1\0\7\0\1\0\4\0\1\0\4\0\1\0\1\0\1\0"+
    "\12\0\1\0\21\0\5\0\3\0\1\0\5\0\1\0\21\0\u1144\0"+
    "\ua6d7\0\51\0\u1035\0\13\0\336\0\u3fe2\0\u021e\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u05f0\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\2\4\1\5\1\6\2\2"+
    "\1\7\1\10\1\11\2\1\13\2\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\33\2\0"+
    "\1\34\1\35\1\36\1\0\1\37\1\40\2\2\1\41"+
    "\1\2\1\0\1\7\1\42\1\43\1\44\2\0\1\45"+
    "\3\0\16\2\1\46\3\2\1\47\1\0\1\50\1\51"+
    "\1\0\1\52\1\53\1\54\1\55\1\56\1\57\1\60"+
    "\1\61\1\62\1\63\1\64\1\65\1\66\1\35\1\0"+
    "\2\36\3\0\3\2\1\67\6\2\1\70\10\2\1\71"+
    "\1\2\1\72\1\73\1\74\1\75\1\76\1\77\1\36"+
    "\2\0\1\36\1\100\10\2\1\101\1\102\1\103\2\2"+
    "\1\104\3\2\1\105\1\2\1\0\1\36\2\2\1\106"+
    "\1\2\1\107\1\110\3\2\1\111\4\2\1\0\1\2"+
    "\1\112\1\113\3\2\1\114\1\115\1\116\1\2\1\0"+
    "\1\2\1\117\2\2\1\120\1\0\2\2\1\121\1\0"+
    "\1\122\1\2\1\0\1\2\1\123";

  private static int [] zzUnpackAction() {
    int [] result = new int[204];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\76\0\174\0\272\0\370\0\76\0\u0136\0\u0174"+
    "\0\u01b2\0\u01f0\0\u022e\0\u026c\0\u02aa\0\u02e8\0\u0326\0\u0364"+
    "\0\u03a2\0\u03e0\0\u041e\0\u045c\0\u049a\0\u04d8\0\u0516\0\u0554"+
    "\0\u0592\0\u05d0\0\u060e\0\u064c\0\u068a\0\u06c8\0\76\0\76"+
    "\0\u0706\0\u0744\0\76\0\76\0\u0782\0\u07c0\0\76\0\76"+
    "\0\u07fe\0\76\0\76\0\u083c\0\u087a\0\u08b8\0\76\0\u08f6"+
    "\0\u0934\0\u0972\0\76\0\76\0\u09b0\0\u09ee\0\174\0\u0a2c"+
    "\0\u0a6a\0\u0aa8\0\u0ae6\0\76\0\76\0\u0b24\0\u02e8\0\76"+
    "\0\u0b62\0\u0326\0\u0ba0\0\u0bde\0\u0c1c\0\u0c5a\0\u0c98\0\u0cd6"+
    "\0\u0d14\0\u0d52\0\u0d90\0\u0dce\0\u0e0c\0\u0e4a\0\u0e88\0\u0ec6"+
    "\0\u0f04\0\u0f42\0\u0f80\0\u0fbe\0\u0ffc\0\76\0\u103a\0\76"+
    "\0\76\0\u1078\0\76\0\76\0\76\0\76\0\76\0\76"+
    "\0\u10b6\0\76\0\76\0\u10f4\0\76\0\76\0\u1132\0\u1170"+
    "\0\u11ae\0\u11ec\0\u122a\0\u1268\0\u12a6\0\u12e4\0\u1322\0\u1360"+
    "\0\u139e\0\76\0\u13dc\0\u141a\0\u1458\0\u1496\0\u14d4\0\u1512"+
    "\0\174\0\u1550\0\u158e\0\u15cc\0\u160a\0\u1648\0\u1686\0\u16c4"+
    "\0\u1702\0\174\0\u1740\0\174\0\76\0\76\0\76\0\76"+
    "\0\76\0\76\0\u177e\0\u17bc\0\u17fa\0\174\0\u1838\0\u1876"+
    "\0\u18b4\0\u18f2\0\u1930\0\u196e\0\u19ac\0\u19ea\0\174\0\174"+
    "\0\174\0\u1a28\0\u1a66\0\174\0\u1aa4\0\u1ae2\0\u1b20\0\174"+
    "\0\u1b5e\0\u1b9c\0\u1bda\0\u1c18\0\u1c56\0\174\0\u1c94\0\174"+
    "\0\174\0\u1cd2\0\u1d10\0\u1d4e\0\174\0\u1d8c\0\u1dca\0\u1e08"+
    "\0\u1e46\0\u1e84\0\u1ec2\0\174\0\174\0\u1f00\0\u1f3e\0\u1f7c"+
    "\0\174\0\174\0\174\0\u1fba\0\u1ff8\0\u2036\0\174\0\u2074"+
    "\0\u20b2\0\174\0\u20f0\0\u212e\0\u216c\0\174\0\u21aa\0\174"+
    "\0\u21e8\0\u2226\0\u2264\0\174";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[204];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\2\6\1\7\1\10\1\3"+
    "\1\11\3\3\1\12\1\13\1\3\1\4\2\3\1\14"+
    "\1\15\1\16\2\2\1\6\1\17\1\20\1\21\2\3"+
    "\1\22\1\23\1\3\1\24\1\25\1\26\1\27\1\3"+
    "\1\30\1\31\2\3\1\32\1\33\1\34\1\35\1\6"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\47\1\50\1\51\1\52\1\53\1\54\77\0"+
    "\2\3\5\0\13\3\1\0\1\55\5\0\21\3\25\0"+
    "\1\4\6\0\1\56\3\0\1\57\1\4\1\0\1\4"+
    "\1\0\1\56\1\0\1\60\55\0\1\6\77\0\1\61"+
    "\1\62\45\0\1\63\75\0\1\64\21\0\2\3\5\0"+
    "\4\3\1\65\6\3\1\0\1\55\5\0\21\3\24\0"+
    "\2\3\5\0\1\66\12\3\1\0\1\55\5\0\5\3"+
    "\1\67\6\3\1\70\4\3\25\0\1\71\6\0\1\56"+
    "\4\0\1\72\1\0\1\72\1\73\1\56\1\0\1\60"+
    "\74\0\1\74\31\0\1\75\22\0\1\60\13\0\1\60"+
    "\1\0\1\60\3\0\1\76\51\0\25\77\1\100\1\101"+
    "\47\77\26\102\1\103\2\102\1\100\44\102\1\0\2\3"+
    "\5\0\13\3\1\0\1\55\5\0\1\3\1\104\17\3"+
    "\24\0\2\3\5\0\1\3\1\105\11\3\1\0\1\55"+
    "\5\0\2\3\1\106\16\3\24\0\2\3\5\0\1\3"+
    "\1\107\11\3\1\0\1\55\5\0\21\3\24\0\2\3"+
    "\5\0\13\3\1\0\1\55\5\0\2\3\1\110\3\3"+
    "\1\111\4\3\1\112\5\3\24\0\2\3\5\0\13\3"+
    "\1\0\1\55\5\0\17\3\1\113\1\3\24\0\2\3"+
    "\5\0\13\3\1\0\1\55\5\0\2\3\1\114\10\3"+
    "\1\115\2\3\1\116\2\3\24\0\2\3\5\0\1\3"+
    "\1\117\1\120\10\3\1\0\1\55\5\0\7\3\1\121"+
    "\11\3\24\0\2\3\5\0\13\3\1\0\1\55\5\0"+
    "\13\3\1\122\5\3\24\0\2\3\5\0\13\3\1\0"+
    "\1\55\5\0\2\3\1\123\16\3\24\0\2\3\5\0"+
    "\13\3\1\0\1\55\5\0\2\3\1\124\16\3\24\0"+
    "\2\3\5\0\13\3\1\0\1\55\5\0\2\3\1\125"+
    "\16\3\76\0\1\126\1\0\1\127\74\0\1\130\1\131"+
    "\10\0\1\132\64\0\1\133\75\0\1\134\75\0\1\135"+
    "\4\0\1\136\36\0\1\137\31\0\1\140\5\0\1\141"+
    "\67\0\1\142\75\0\1\143\11\0\1\144\63\0\1\145"+
    "\75\0\1\146\21\0\1\147\6\0\6\147\1\0\1\147"+
    "\1\0\2\147\7\0\21\147\25\0\1\150\13\0\1\150"+
    "\1\0\1\150\2\0\1\151\27\0\1\151\24\0\1\60"+
    "\6\0\1\56\3\0\1\57\1\60\1\0\1\60\1\0"+
    "\1\56\53\0\4\152\1\153\71\152\6\154\1\155\1\156"+
    "\66\154\1\0\2\3\5\0\13\3\1\0\1\55\5\0"+
    "\11\3\1\157\7\3\24\0\2\3\5\0\13\3\1\0"+
    "\1\55\5\0\7\3\1\160\11\3\24\0\2\3\5\0"+
    "\13\3\1\0\1\55\5\0\15\3\1\161\3\3\25\0"+
    "\1\71\6\0\1\56\4\0\1\71\1\0\1\71\1\0"+
    "\1\56\1\0\1\60\53\0\1\71\6\0\1\56\4\0"+
    "\1\72\1\0\1\72\1\0\1\56\1\0\1\60\53\0"+
    "\1\73\6\0\1\73\4\0\3\73\1\0\1\73\7\0"+
    "\1\73\1\0\1\73\1\0\2\73\2\0\1\73\57\0"+
    "\1\162\51\0\3\77\2\0\22\77\2\0\45\77\3\102"+
    "\2\0\22\102\2\0\45\102\1\0\2\3\5\0\1\3"+
    "\1\163\11\3\1\0\1\55\5\0\21\3\24\0\2\3"+
    "\5\0\13\3\1\0\1\55\5\0\7\3\1\164\11\3"+
    "\24\0\2\3\5\0\1\165\12\3\1\0\1\55\5\0"+
    "\21\3\24\0\2\3\5\0\13\3\1\0\1\55\5\0"+
    "\5\3\1\166\13\3\24\0\2\3\5\0\4\3\1\167"+
    "\6\3\1\0\1\55\5\0\21\3\24\0\2\3\5\0"+
    "\1\170\12\3\1\0\1\55\5\0\21\3\24\0\2\3"+
    "\5\0\13\3\1\0\1\55\5\0\1\3\1\171\17\3"+
    "\24\0\2\3\5\0\13\3\1\0\1\55\5\0\15\3"+
    "\1\172\3\3\24\0\2\3\5\0\13\3\1\0\1\55"+
    "\5\0\11\3\1\173\7\3\24\0\2\3\5\0\1\174"+
    "\12\3\1\0\1\55\5\0\21\3\24\0\2\3\5\0"+
    "\13\3\1\0\1\55\5\0\2\3\1\175\16\3\24\0"+
    "\2\3\5\0\4\3\1\176\6\3\1\0\1\55\5\0"+
    "\21\3\24\0\2\3\5\0\5\3\1\177\5\3\1\0"+
    "\1\55\5\0\21\3\24\0\2\3\5\0\13\3\1\0"+
    "\1\55\5\0\1\3\1\200\17\3\24\0\2\3\5\0"+
    "\13\3\1\0\1\55\5\0\7\3\1\201\11\3\24\0"+
    "\2\3\5\0\13\3\1\0\1\55\5\0\15\3\1\202"+
    "\3\3\24\0\2\3\5\0\13\3\1\0\1\55\5\0"+
    "\10\3\1\203\10\3\24\0\2\3\5\0\13\3\1\0"+
    "\1\55\5\0\1\3\1\204\17\3\101\0\1\205\74\0"+
    "\1\206\1\207\74\0\1\210\75\0\1\211\21\0\2\147"+
    "\5\0\13\147\7\0\21\147\25\0\1\150\12\0\1\57"+
    "\1\150\1\0\1\150\57\0\1\150\13\0\1\150\1\0"+
    "\1\150\55\0\4\152\1\212\71\152\10\0\1\213\65\0"+
    "\6\154\1\0\1\156\66\154\7\0\1\214\74\0\1\215"+
    "\70\0\2\3\5\0\1\3\1\216\11\3\1\0\1\55"+
    "\5\0\21\3\24\0\2\3\5\0\1\3\1\217\11\3"+
    "\1\0\1\55\5\0\21\3\24\0\2\3\5\0\13\3"+
    "\1\0\1\55\5\0\13\3\1\220\5\3\24\0\2\3"+
    "\5\0\13\3\1\0\1\55\5\0\2\3\1\221\16\3"+
    "\24\0\2\3\5\0\13\3\1\0\1\55\5\0\6\3"+
    "\1\222\12\3\24\0\2\3\5\0\13\3\1\0\1\55"+
    "\5\0\12\3\1\223\6\3\24\0\2\3\5\0\1\3"+
    "\1\224\11\3\1\0\1\55\5\0\2\3\1\225\16\3"+
    "\24\0\2\3\5\0\4\3\1\226\6\3\1\0\1\55"+
    "\5\0\21\3\24\0\2\3\5\0\13\3\1\0\1\55"+
    "\5\0\10\3\1\227\10\3\24\0\2\3\5\0\1\3"+
    "\1\230\11\3\1\0\1\55\5\0\21\3\24\0\2\3"+
    "\5\0\1\3\1\231\11\3\1\0\1\55\5\0\21\3"+
    "\24\0\2\3\5\0\13\3\1\0\1\55\5\0\7\3"+
    "\1\232\1\3\1\233\7\3\24\0\2\3\5\0\1\234"+
    "\12\3\1\0\1\55\5\0\21\3\24\0\2\3\5\0"+
    "\1\3\1\235\11\3\1\0\1\55\5\0\21\3\24\0"+
    "\2\3\5\0\13\3\1\0\1\55\5\0\7\3\1\236"+
    "\11\3\24\0\2\3\5\0\13\3\1\0\1\55\5\0"+
    "\6\3\1\237\12\3\24\0\2\3\5\0\13\3\1\0"+
    "\1\55\5\0\13\3\1\240\5\3\24\0\2\3\5\0"+
    "\13\3\1\0\1\55\5\0\3\3\1\241\15\3\34\0"+
    "\1\242\72\0\1\212\72\0\1\243\1\212\72\0\2\3"+
    "\5\0\13\3\1\0\1\55\5\0\1\3\1\244\17\3"+
    "\24\0\2\3\5\0\13\3\1\0\1\55\5\0\1\3"+
    "\1\245\17\3\24\0\2\3\5\0\13\3\1\0\1\55"+
    "\5\0\3\3\1\246\15\3\24\0\2\3\5\0\13\3"+
    "\1\0\1\55\5\0\1\3\1\247\17\3\24\0\2\3"+
    "\5\0\1\3\1\250\11\3\1\0\1\55\5\0\21\3"+
    "\24\0\2\3\5\0\13\3\1\0\1\55\5\0\1\3"+
    "\1\251\17\3\24\0\2\3\5\0\13\3\1\0\1\55"+
    "\5\0\6\3\1\252\12\3\24\0\2\3\5\0\13\3"+
    "\1\0\1\55\5\0\7\3\1\253\11\3\24\0\2\3"+
    "\5\0\5\3\1\254\5\3\1\0\1\55\5\0\21\3"+
    "\24\0\2\3\5\0\13\3\1\0\1\55\5\0\7\3"+
    "\1\255\11\3\24\0\2\3\5\0\13\3\1\0\1\55"+
    "\5\0\10\3\1\256\10\3\24\0\2\3\5\0\13\3"+
    "\1\0\1\55\5\0\10\3\1\257\10\3\24\0\2\3"+
    "\5\0\13\3\1\0\1\55\5\0\10\3\1\260\10\3"+
    "\24\0\2\3\5\0\13\3\1\0\1\55\5\0\2\3"+
    "\1\261\16\3\35\0\1\262\67\0\1\212\72\0\2\3"+
    "\5\0\13\3\1\0\1\55\5\0\5\3\1\263\13\3"+
    "\24\0\2\3\5\0\13\3\1\0\1\55\5\0\7\3"+
    "\1\264\11\3\24\0\2\3\5\0\1\265\12\3\1\0"+
    "\1\55\5\0\21\3\24\0\2\3\5\0\4\3\1\266"+
    "\6\3\1\0\1\55\5\0\21\3\24\0\2\3\5\0"+
    "\13\3\1\0\1\55\5\0\16\3\1\267\2\3\24\0"+
    "\2\3\5\0\1\270\12\3\1\0\1\55\5\0\21\3"+
    "\24\0\2\3\5\0\13\3\1\0\1\55\5\0\7\3"+
    "\1\271\11\3\24\0\2\3\5\0\13\3\1\0\1\55"+
    "\5\0\16\3\1\272\2\3\24\0\2\3\5\0\13\3"+
    "\1\0\1\55\5\0\7\3\1\273\11\3\24\0\2\3"+
    "\5\0\13\3\1\0\1\55\5\0\12\3\1\274\6\3"+
    "\36\0\1\275\63\0\2\3\5\0\13\3\1\0\1\55"+
    "\5\0\2\3\1\276\16\3\24\0\2\3\5\0\13\3"+
    "\1\0\1\55\5\0\7\3\1\277\11\3\24\0\2\3"+
    "\5\0\13\3\1\0\1\55\5\0\1\3\1\300\17\3"+
    "\24\0\2\3\5\0\13\3\1\0\1\55\5\0\6\3"+
    "\1\301\12\3\24\0\2\3\5\0\1\3\1\302\11\3"+
    "\1\0\1\55\5\0\21\3\37\0\1\303\62\0\2\3"+
    "\5\0\13\3\1\0\1\55\5\0\10\3\1\304\10\3"+
    "\24\0\2\3\5\0\13\3\1\0\1\55\5\0\13\3"+
    "\1\305\5\3\24\0\2\3\5\0\1\3\1\306\11\3"+
    "\1\0\1\55\5\0\21\3\40\0\1\307\61\0\2\3"+
    "\5\0\1\3\1\310\11\3\1\0\1\55\5\0\21\3"+
    "\24\0\2\3\5\0\13\3\1\0\1\55\5\0\6\3"+
    "\1\311\12\3\33\0\1\312\66\0\2\3\5\0\13\3"+
    "\1\0\1\55\5\0\12\3\1\313\6\3\34\0\1\212"+
    "\65\0\2\3\5\0\13\3\1\0\1\55\5\0\16\3"+
    "\1\314\2\3\23\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[8866];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\1\11\30\1\2\11\2\1\2\11"+
    "\2\1\2\11\1\1\2\11\1\1\2\0\1\11\2\1"+
    "\1\0\2\11\4\1\1\0\2\1\2\11\2\0\1\11"+
    "\3\0\22\1\1\11\1\0\2\11\1\0\6\11\1\1"+
    "\2\11\1\1\2\11\2\1\1\0\2\1\3\0\3\1"+
    "\1\11\22\1\6\11\2\0\25\1\1\0\17\1\1\0"+
    "\12\1\1\0\5\1\1\0\3\1\1\0\2\1\1\0"+
    "\2\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[204];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    /* Para criar um novo java_cup.runtime.Symbol com informação sobre
       o token atual, mas esse tipo de token não tem valor associado.
    */
    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }

    /* Também cria um new java_cup.runtime.Symbol Com informação
       sobre o token atual, mas esse objeto tem um valor. */
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexical(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2324) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
              {
                return symbol(sym.EOF);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new RuntimeException("Erro léxico caractere ilegal:" + yytext() +
                                                              " na linha " + yyline + ", " + " coluna " + yycolumn);
            }
          case 84: break;
          case 2: 
            { return symbol(sym.IDENTIFIER, yytext());
            }
          case 85: break;
          case 3: 
            { return symbol(sym.INTEGER_LITERAL, new Integer(yytext()));
            }
          case 86: break;
          case 4: 
            { /* Ignore */
            }
          case 87: break;
          case 5: 
            { return symbol(sym.DIV);
            }
          case 88: break;
          case 6: 
            { return symbol(sym.MULT);
            }
          case 89: break;
          case 7: 
            { return symbol(sym.OCTAL_LITERAL, yytext());
            }
          case 90: break;
          case 8: 
            { return symbol(sym.MINUS);
            }
          case 91: break;
          case 9: 
            { return symbol(sym.DOT);
            }
          case 92: break;
          case 10: 
            { return symbol(sym.PLUS);
            }
          case 93: break;
          case 11: 
            { return symbol(sym.AND);
            }
          case 94: break;
          case 12: 
            { return symbol(sym.EQ);
            }
          case 95: break;
          case 13: 
            { return symbol(sym.NOT);
            }
          case 96: break;
          case 14: 
            { return symbol(sym.LPAREN);
            }
          case 97: break;
          case 15: 
            { return symbol(sym.RPAREN);
            }
          case 98: break;
          case 16: 
            { return symbol(sym.PIPE);
            }
          case 99: break;
          case 17: 
            { return symbol(sym.LT);
            }
          case 100: break;
          case 18: 
            { return symbol(sym.LBRACK);
            }
          case 101: break;
          case 19: 
            { return symbol(sym.RBRACK);
            }
          case 102: break;
          case 20: 
            { return symbol(sym.CIRCU);
            }
          case 103: break;
          case 21: 
            { return symbol(sym.GT);
            }
          case 104: break;
          case 22: 
            { return symbol(sym.LBRACE);
            }
          case 105: break;
          case 23: 
            { return symbol(sym.RBRACE);
            }
          case 106: break;
          case 24: 
            { return symbol(sym.COLON);
            }
          case 107: break;
          case 25: 
            { return symbol(sym.COMMA);
            }
          case 108: break;
          case 26: 
            { return symbol(sym.SEMICOLON);
            }
          case 109: break;
          case 27: 
            { return symbol(sym.MOD);
            }
          case 110: break;
          case 28: 
            { return symbol(sym.IMAGINARY_LITERAL, yytext());
            }
          case 111: break;
          case 29: 
            { return symbol(sym.FLOATING_POINT_LITERAL, new Float(yytext()));
            }
          case 112: break;
          case 30: 
            { /* ignore */
            }
          case 113: break;
          case 31: 
            { return symbol(sym.DIVEQ);
            }
          case 114: break;
          case 32: 
            { return symbol(sym.MULTEQ);
            }
          case 115: break;
          case 33: 
            { return symbol(sym.IF);
            }
          case 116: break;
          case 34: 
            { return symbol(sym.HEX_LITERAL, yytext());
            }
          case 117: break;
          case 35: 
            { return symbol(sym.MINUSMINUS);
            }
          case 118: break;
          case 36: 
            { return symbol(sym.MINUSEQ);
            }
          case 119: break;
          case 37: 
            { return symbol(sym.STRING_LITERAL, yytext());
            }
          case 120: break;
          case 38: 
            { return symbol(sym.GO);
            }
          case 121: break;
          case 39: 
            { return symbol(sym.PLUSPLUS);
            }
          case 122: break;
          case 40: 
            { return symbol(sym.ANDAND);
            }
          case 123: break;
          case 41: 
            { return symbol(sym.ANDEQ);
            }
          case 124: break;
          case 42: 
            { return symbol(sym.EQEQ);
            }
          case 125: break;
          case 43: 
            { return symbol(sym.NOTEQ);
            }
          case 126: break;
          case 44: 
            { return symbol(sym.PIPEEQ);
            }
          case 127: break;
          case 45: 
            { return symbol(sym.PIPEPIPE);
            }
          case 128: break;
          case 46: 
            { return symbol(sym.ARRLEFT);
            }
          case 129: break;
          case 47: 
            { return symbol(sym.LTEQ);
            }
          case 130: break;
          case 48: 
            { return symbol(sym.LSHIFT);
            }
          case 131: break;
          case 49: 
            { return symbol(sym.CIRCUEQ);
            }
          case 132: break;
          case 50: 
            { return symbol(sym.GTEQ);
            }
          case 133: break;
          case 51: 
            { return symbol(sym.RSHIFT);
            }
          case 134: break;
          case 52: 
            { return symbol(sym.COLONEQ);
            }
          case 135: break;
          case 53: 
            { return symbol(sym.MODEQ);
            }
          case 136: break;
          case 54: 
            { return symbol(sym.QUALIFIED_IDENTIFIER, yytext());
            }
          case 137: break;
          case 55: 
            { return symbol(sym.ELLIPSIS);
            }
          case 138: break;
          case 56: 
            { return symbol(sym.FOR);
            }
          case 139: break;
          case 57: 
            { return symbol(sym.MAP);
            }
          case 140: break;
          case 58: 
            { return symbol(sym.VAR);
            }
          case 141: break;
          case 59: 
            { return symbol(sym.PLUSEQ);
            }
          case 142: break;
          case 60: 
            { return symbol(sym.ANDNOTEQ);
            }
          case 143: break;
          case 61: 
            { return symbol(sym.ANDNOT);
            }
          case 144: break;
          case 62: 
            { return symbol(sym.LSHIFTEQ);
            }
          case 145: break;
          case 63: 
            { return symbol(sym.RSHIFTEQ);
            }
          case 146: break;
          case 64: 
            { return symbol(sym.ELSE);
            }
          case 147: break;
          case 65: 
            { return symbol(sym.FUNC);
            }
          case 148: break;
          case 66: 
            { return symbol(sym.TYPE);
            }
          case 149: break;
          case 67: 
            { return symbol(sym.CASE);
            }
          case 150: break;
          case 68: 
            { return symbol(sym.CHAN);
            }
          case 151: break;
          case 69: 
            { return symbol(sym.GOTO);
            }
          case 152: break;
          case 70: 
            { return symbol(sym.BREAK);
            }
          case 153: break;
          case 71: 
            { return symbol(sym.RANGE);
            }
          case 154: break;
          case 72: 
            { return symbol(sym.DEFER);
            }
          case 155: break;
          case 73: 
            { return symbol(sym.CONST);
            }
          case 156: break;
          case 74: 
            { return symbol(sym.IMPORT);
            }
          case 157: break;
          case 75: 
            { return symbol(sym.RETURN);
            }
          case 158: break;
          case 76: 
            { return symbol(sym.SELECT);
            }
          case 159: break;
          case 77: 
            { return symbol(sym.SWITCH);
            }
          case 160: break;
          case 78: 
            { return symbol(sym.STRUCT);
            }
          case 161: break;
          case 79: 
            { return symbol(sym.DEFAULT);
            }
          case 162: break;
          case 80: 
            { return symbol(sym.PACKAGE);
            }
          case 163: break;
          case 81: 
            { return symbol(sym.CONTINUE);
            }
          case 164: break;
          case 82: 
            { return symbol(sym.INTERFACE);
            }
          case 165: break;
          case 83: 
            { return symbol(sym.FALLTHROUGH);
            }
          case 166: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java Lexical [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid? 
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        Lexical scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new Lexical(reader);
          while ( !scanner.zzAtEOF ) scanner.next_token();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
