
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jul 07 20:20:16 GFT 2018
//----------------------------------------------------

package go.core;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SHORT = 29;
  public static final int IDENTIFIER = 101;
  public static final int ANDEQ = 89;
  public static final int GT = 64;
  public static final int TYPE = 21;
  public static final int GO = 9;
  public static final int CONST = 17;
  public static final int NOTEQ = 73;
  public static final int PLUSEQ = 84;
  public static final int FUNC = 4;
  public static final int RBRACK = 36;
  public static final int DEFER = 8;
  public static final int COMMA = 40;
  public static final int RBRACE = 44;
  public static final int ANDNOTEQ = 90;
  public static final int RPAREN = 47;
  public static final int LBRACK = 35;
  public static final int PIPEPIPE = 51;
  public static final int LT = 63;
  public static final int ANDAND = 78;
  public static final int OROR = 79;
  public static final int DOUBLE = 34;
  public static final int STRUCT = 11;
  public static final int LBRACE = 43;
  public static final int LPAREN = 46;
  public static final int XOREQ = 91;
  public static final int INTEGER_LITERAL = 93;
  public static final int NOT = 57;
  public static final int VAR = 26;
  public static final int FLOAT = 33;
  public static final int GOTO = 14;
  public static final int URSHIFTEQ = 88;
  public static final int PACKAGE = 15;
  public static final int COMP = 56;
  public static final int INFUNCEQ = 70;
  public static final int EQ = 45;
  public static final int CIRCU = 67;
  public static final int BOOLEAN_LITERAL = 95;
  public static final int MOD = 59;
  public static final int SELECT = 6;
  public static final int FALLTHROUGH = 18;
  public static final int PIPE = 49;
  public static final int LONG = 31;
  public static final int CIRCUEQ = 68;
  public static final int PLUS = 54;
  public static final int QUESTION = 80;
  public static final int OCTAL_LITERAL = 99;
  public static final int INTERFACE = 5;
  public static final int CHAR = 32;
  public static final int BOOLEAN = 27;
  public static final int CHAN = 12;
  public static final int SWITCH = 16;
  public static final int FOR = 23;
  public static final int RSHIFTEQ = 87;
  public static final int DIV = 58;
  public static final int RETURN = 25;
  public static final int MULT = 39;
  public static final int IMAGINARY_LITERAL = 98;
  public static final int ANDNOT = 75;
  public static final int ELSE = 13;
  public static final int BREAK = 2;
  public static final int GTEQ = 66;
  public static final int DOT = 37;
  public static final int INT = 30;
  public static final int MAP = 10;
  public static final int STRING_LITERAL = 100;
  public static final int EQEQ = 72;
  public static final int EOF = 0;
  public static final int SEMICOLON = 38;
  public static final int DEFAULT = 3;
  public static final int MULTEQ = 81;
  public static final int IMPORT = 24;
  public static final int MINUS = 55;
  public static final int LTEQ = 65;
  public static final int OR = 77;
  public static final int error = 1;
  public static final int URSHIFT = 62;
  public static final int DIVEQ = 82;
  public static final int LSHIFTEQ = 86;
  public static final int CONTINUE = 22;
  public static final int IF = 19;
  public static final int MODEQ = 83;
  public static final int MINUSMINUS = 53;
  public static final int COLON = 48;
  public static final int ARRLEFT = 69;
  public static final int HEX_LITERAL = 97;
  public static final int CHARACTER_LITERAL = 96;
  public static final int RBRACKET = 42;
  public static final int OREQ = 92;
  public static final int CASE = 7;
  public static final int PLUSPLUS = 52;
  public static final int RSHIFT = 61;
  public static final int RANGE = 20;
  public static final int BYTE = 28;
  public static final int AND = 74;
  public static final int ELLIPSIS = 71;
  public static final int LBRACKET = 41;
  public static final int LSHIFT = 60;
  public static final int XOR = 76;
  public static final int FLOATING_POINT_LITERAL = 94;
  public static final int MINUSEQ = 85;
  public static final int PIPEEQ = 50;
}

